-- INITIAL TABLE CONSTRUCTION

CREATE TABLE [Product] (
ProductId UNIQUEIDENTIFIER NOT NULL,
ProductName NVARCHAR(50) NOT NULL,
ProductDescription VARCHAR(2000) NOT NULL
CONSTRAINT PK_Product_ProductId PRIMARY KEY (ProductId)
)
GO

CREATE TABLE [Store] (
StoreId UNIQUEIDENTIFIER NOT NULL,
StoreName NVARCHAR(50) NOT NULL,
StoreDescription VARCHAR(2000) NOT NULL
CONSTRAINT PK_Store_StoreId PRIMARY KEY (StoreId)
)
GO

CREATE TABLE [StoreProduct] (
StoreId UNIQUEIDENTIFIER NOT NULL,
ProductId UNIQUEIDENTIFIER NOT NULL
CONSTRAINT PK_StoreProduct PRIMARY KEY (StoreId, ProductId)
)
GO

-- FOREIGN KEY PAIRING

ALTER TABLE [StoreProduct]
ADD CONSTRAINT FK_StoreProduct_Product FOREIGN KEY (ProductId) REFERENCES Product (ProductId)
GO

ALTER TABLE [StoreProduct]
ADD CONSTRAINT FK_StoreProduct_Store FOREIGN KEY (StoreId) REFERENCES Store (StoreId)
GO