-- INITIAL TABLE CONSTRUCTION

CREATE TABLE [Product] (
ProductId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
ProductName NVARCHAR(50) NOT NULL,
ProductDescription VARCHAR(2000) NOT NULL
CONSTRAINT PK_Product_ProductId PRIMARY KEY (ProductId)
)
UPDATE [Product] SET ProductDescription = ''
GO

CREATE TABLE [Store] (
StoreId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
StoreName NVARCHAR(50) NOT NULL,
StoreDescription VARCHAR(2000) NOT NULL
CONSTRAINT PK_Store_StoreId PRIMARY KEY (StoreId)
)
UPDATE [Store] SET StoreDescription = ''
GO

CREATE TABLE [StoreProduct] (
StoreId UNIQUEIDENTIFIER NOT NULL,
ProductId UNIQUEIDENTIFIER NOT NULL,
Stock INTEGER NOT NULL,
Price DECIMAL(4,2) NOT NULL,
CONSTRAINT PK_StoreProduct PRIMARY KEY (StoreId, ProductId)
)
GO

-- FOREIGN KEY PAIRING

ALTER TABLE [StoreProduct]
ADD CONSTRAINT FK_StoreProduct_ProductId FOREIGN KEY (ProductId) REFERENCES Product (ProductId)
GO

ALTER TABLE [StoreProduct]
ADD CONSTRAINT FK_StoreProduct_StoreId FOREIGN KEY (StoreId) REFERENCES Store (StoreId)
GO